# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expec_log_x_cpp <- function(X, phia, zeta, n_quest, n_latent, n_cat) {
    .Call('_mixdir_expec_log_x_cpp', PACKAGE = 'mixdir', X, phia, zeta, n_quest, n_latent, n_cat)
}

update_zeta_cpp <- function(zeta, X, phia, omega, n_ind, n_quest, n_latent, n_cat) {
    .Call('_mixdir_update_zeta_cpp', PACKAGE = 'mixdir', zeta, X, phia, omega, n_ind, n_quest, n_latent, n_cat)
}

update_zeta_dp_cpp <- function(zeta, X, phia, kappa1, kappa2, n_ind, n_quest, n_latent, n_cat) {
    .Call('_mixdir_update_zeta_dp_cpp', PACKAGE = 'mixdir', zeta, X, phia, kappa1, kappa2, n_ind, n_quest, n_latent, n_cat)
}

